---
title: Research
csl: apa-cv.csl
bibliography: references.bib
suppress-bibliography: true
link-citations: false
citations-hover: false
---

## Peer reviewed publications

-   @pfanderTrustingForgettingImpressive2025a ([<i class="fas fa-file-pdf"></i> preprint](https://osf.io/preprints/osf/argq5_v2) \| [<i class="fas fa-file-pdf"></i> published version](pdfs/2025_impressive.pdf) \| [<i class="fab fa-github"></i> code & data](https://github.com/janpfander/impressive_science))

-   @pfanderQuasiuniversalAcceptanceBasic2025b ([<i class="fas fa-file-pdf"></i> preprint](https://osf.io/preprints/osf/qc43v_v3) \| [<i class="fas fa-file-pdf"></i> published version](pdfs/2025_quasi_universal.pdf) \| [<i class="fab fa-github"></i> code & data](https://github.com/janpfander/everyone_trusts_science_abit))

-   @pfanderSpottingFalseNews2025 ([<i class="fas fa-file-pdf"></i> preprint](https://osf.io/preprints/osf/n9h4y) \| [<i class="fas fa-file-pdf"></i> published version](pdfs/2025_spotting_false.pdf) \| [<i class="fab fa-github"></i> code & data](https://github.com/janpfa/meta_news_judgement))

-   @pfanderHowWiseCrowd2025 ([<i class="fas fa-file-pdf"></i> preprint](pdfs/2025_cognition_preprint.pdf) \| [<i class="fas fa-file-pdf"></i> published version](pdfs/2025_how_wise.pdf) \| [<i class="fab fa-github"></i> code & data](https://github.com/janpfander/consensus_trust.git))

## Large Collaborations

-   @colognaTrustScientistsTheir2025 ([<i class="fas fa-file-pdf"></i> preprint](https://doi.org/10.31219/osf.io/6ay7s))

-   @medePerceptionsScienceScience2025 ([<i class="fas fa-file-pdf"></i> preprint](https://doi.org/10.31234/osf.io/jktsy))

## Conference Proceedings

-   @pfanderHowWiseCrowd2024([<i class="fas fa-file-pdf"></i> pdf](pdfs/2024_how_wise_cogsci.pdf) \| [<i class="fa-solid fa-person-chalkboard"></i>poster](talks/cogsci_2024.pdf) \| [<i class="fab fa-github"></i> code & data](https://github.com/janpfander/consensus_trust.git))

## Working papers

-   @pfanderRationalImpressionAccount2025a (*submitted*)
-   @pfanderStudyingTrustScience2025 (*submitted*)
-   @pfanderFrenchTrustMore2025 (*submitted*)

## Talks

### 2025

-   Pfänder, J., & Altay, S. (2025, June). *Belief in & interventions against misinformation*. 15th Annual Conference of the European Political Science Association, Madrid. ([<i class="fa-solid fa-person-chalkboard"></i>slides](https://janpfander.github.io/meta_misinformation_interventions/presentations/presentations.html))

-   Pfänder, J., & Mercier, H. (2025, May). *The rational impression account of trust in science*. Explaining culture: an interdisciplinary approach, Paris.

-   Pfänder, J., & Mercier, H. (2025, March). *Trust in science*. Paris School of International Affairs (Sciences Po), Paris.

-   Pfänder, J., & Altay, S. (2025, March). *Spotting False News and Doubting True News. A Meta-Analysis of News Judgments*. Infox sur seine, Paris.

### 2024

-   Pfänder, J. (2024, July). *How wise is the crowd: Can we infer people are accurate and competent merely because they agree with each other?* 46th Annual Meeting of the Cognitive Science Society, Rotterdam.

-   Pfänder, J. (2024, June). *Processus sous-tendant la confiance dans la science.* 5ème édition des Rencontres Jeunes Chercheur·euse·s, Grenoble.

-   Pfänder, J., & Altay, S. (2024, February). *Spotting False News and Doubting True News: A Meta-Analysis of News Judgments.* EDMO Scientific Conference on Disinformation, Amsterdam.
